### ISSUE TITLE
quickstart crashes when there isn't a webdefault.xml

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#135]
Added to my appengine-web.xml:
    <beta-settings>
      <setting name="java_quickstart" value="true" />
    </beta-settings>

did a mvn gcloud:run on my Mac on my [project](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vm-gae) and it generated a quickstart.xml and crashed. Looking at getFilteredQuickstartDoc in Application.java it appears that it doesn't check for a missing webdefault.xml  (I've had no other problems not having a webdefault.xml before)

`Unable to stage:
java.lang.RuntimeException: Failed to generate quickstart-web.xml.
	at com.google.appengine.tools.admin.Application.createQuickstartWebXml(Application.java:1457)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:775)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:736)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:532)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:485)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2523)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:360)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:222)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:127)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:123)
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.executeAppCfgStagingCommand(AbstractGcloudMojo.java:598)
	at com.google.appengine.gcloudapp.GCloudAppRun.getCommand(GCloudAppRun.java:350)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:301)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
com.google.appengine.tools.admin.AdminException: Unable to stage app: Failed to generate quickstart-web.xml.
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:536)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:485)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2523)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:360)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:222)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:127)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:123)
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.executeAppCfgStagingCommand(AbstractGcloudMojo.java:598)
	at com.google.appengine.gcloudapp.GCloudAppRun.getCommand(GCloudAppRun.java:350)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:301)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to generate quickstart-web.xml.
	at com.google.appengine.tools.admin.Application.createQuickstartWebXml(Application.java:1457)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:775)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:736)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:532)
	... 31 more`

**Comment by ludoch** [comment]
Not related to webdefault.xml but the fact that there is a servlet defined as:

@WebServlet(name="ok", urlPatterns={"/_ah/health", "/_ah/start", "/_ah/stop"} )

So it overrides the servlets we define in webdefault.xml

For now, I do not think you need this so remove this servlet. But it is not a good behavior anyway.

**Comment by ludoch** [comment]
Maybe related to our trimming process of these servlets before generating the app.yaml

**Comment by ludoch** [comment]
Haha, also the Weblistener annotation is causing error!

**Comment by janbartel** [comment]
@ludoch is there an issue with the @WebListener annotation that you'd like me to look into?

**Comment by janbartel** [comment]
@ludoch I'm assigning you this issue so you can comment on it. From your comments on 17th December it looks like this is not a jetty issue, but related to the generation of the app.yaml?
