### ISSUE TITLE
lastest Jetty 9.3.7.v20160115 causes issue with the quickstart step (done with the previous jetty for now)

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#171]
See the app log in a image build with the async branch, and quickstart enabled in the appengine-web.xml (stage3 of the sample)

[2/11/16, 12:15 PM] : org.eclipse.jetty.webapp.WebAppContext doStart: Failed startup of context c.g.a.v.j.VmRuntimeWebAppContext@7fc2413d{/,file:///var/lib/jetty/webapps/root/,STARTING}{/root/} java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83) at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70) at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:403) at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339) at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772) at or
[2/11/16, 12:15 PM] Les Vogel (lesv@google.com): org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435) Caused by: java.net.MalformedURLException: invalid url: /var/lib/jetty/webapps/root/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld (java.net.MalformedURLException: no protocol: /var/lib/jetty/webapps/root/WEB-INF/lib/jstl-1.2.jar) at java.net.URL.<init>(URL.java:620) at java.net.URL.<init>(URL.java:483) at java.net.URL.<init>(URL.java:432) at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:166) at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:149) at org.eclipse.jetty.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:134) ... 24 more Caused by: java.lang.NullPointerException: invalid url: /var/lib/jetty/webapps/root/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld (java.net.MalformedURLException: no protocol: /var/lib/jetty/webapps/root/WEB-INF/lib/jstl-1.2.jar) at sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:178) at sun.net.www.protocol.jar.Handler.parseURL(Handler.java:151) at java.net.URL.<init>(URL.java:615) ...

**Comment by ludoch** [comment]
Just downgrading in the image to the previous version seems to work, so seems related to https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/commit/d3dc0cc4a136773c79fde4e58242acdd12dff74b or the next one that is using the GA release.

**Comment by ludoch** [comment]
generated quickstart xml:
```...
  <context-param>
    <param-name>org.eclipse.jetty.containerInitializers</param-name>
    <param-value><![CDATA[
    "ContainerInitializer{org.eclipse.jetty.apache.jsp.JettyJasperInitializer,interested=[],applicable=[],annotated=[]}"]]></param-value>
  </context-param>
  <context-param>

    <param-name>org.eclipse.jetty.tlds</param-name>
    <param-value><![CDATA[
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x-1_0-rt.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x-1_0.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql-1_0.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/permittedTaglibs.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql-1_0-rt.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/scriptfree.tld",
    "jar:${WAR}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld"]]></param-value>
  </context-param>
  <context-param>```
....
...

**Comment by ludoch** [comment]
Also, when doing only a downgrade of jetty to 9.3.5.v20151012  on the async branch, both quickstart works AND also, I do not see the user server login url issue!https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/164

Or at least, it worked for me in my runs... So maybe random?

So it seems we need to test much more the Jetty upgrade.

For others to test:
The Async Branch is at FROM gcr.io/google_appengine/jetty9-compat:ludoticketnewjetty
https://bugquickstartnewjetty-dot-vmruntime-demo.appspot.com
does not work due to this quickstart bug.

The Async Branch with old jetty is at FROM gcr.io/google_appengine/jetty9-compat:ludoticketoldjetty

https://bugquickstartoldjetty-dot-vmruntime-demo.appspot.com/  works.
Including quickstart and the login url redirect (at least for me)

**Comment by ludoch** [comment]
Well this is not right...
https://lesv-004.appspot.com  starts with https and sign in link.
Sign in, then 
you go to http://0.20160211t173320.lesv-004.appspot.com/guestbook.jsp
which is now https... So same bug

**Comment by gregw** [comment]
The simplest way to see this bug is to look at the logout link on the guestbook page.  For the oldjetty I'm seeing http and 0. in the host, so I can confirm that the #164 bug happens on old jetty as well.   But, I too believe I have seen it work on occasions, but I've never been rigorous enough on those occasions to say definitively - so will focus next time I think it works.

Eitherway, I'm looking at this quickstart issue now.

**Comment by gregw** [comment]
@joakime Can you look at this one for me, as I'm struggling with a slow network that is preventing me from testing my theories.

What I think has happened is that your last changes to the AttributeNormaliser in quickstart switched from having WAR as a URI to a path.    But the SDK version of quickstart is still using URI for encoding, so it changes jar:file:/path/of/war!/resource.tld to jar:${WAR}!/resource.tld
But the latest quickstart is expanding this as a path, so we get jar:/path/of/war!/resource.tld

So if my theory is right, we need to revert quickstart back to encoding WAR as the URI not as the path.  Because generated quickstart files can easily cross jetty versions - we have to be super careful not to break them like this!   If fact we should add a unit test to parse an old quickstart-web.xml that we commit to test resources, so our tests check backward compatibility as well as internal consistency.

If my theory is wrong, let's hangout this afternoon to discuss.

**Comment by gregw** [comment]
@joakime actually looking at it now, it was the original introduction of AttributeNormalizer that switched from URI to Path.     I know path matching is better for depth based comparisons, but the backwards compatibility issue is significant, so we should definitely switch back to URI.

@ludoch if desirable to continue testing on 9.3.7 GA, then I probably can make a temporary hack in the generation of the quickstart to insert the missing "file:/" into the quickstart-web.xml

**Comment by gregw** [comment]
@ludoch If you want to continue testing against 9.3.7, then you can probably just modify the `jetty_run.sh` script to include:

```
sed -i -e 's/jar:${WAR}/jar:file:${WAR}/'   /app/WEB-INF/quickstart-web.xml
```
I think that /app path is correct?    We can remove once we upgrade to 9.3.8.

**Comment by ludoch** [comment]
Cool!
Thanks, and I agree for the regression test... Generated xml should work
across dot releases, as we want to be able to disconnect client dev and
prod pushes.

**Comment by joakime** [comment]
We've made two commits to https://github.com/eclipse/jetty.project relevant to this.

eclipse/jetty.project@bc59c0853d6163cfaec38ba61e3c204445593804 - making WAR a URI reference, not Path
eclipse/jetty.project@30b5fe1c9675257df3ebfbd1f427ef5b033a9081 - ensuring that AttributeNormalizer.normalize() supports normalization of (non-jar, non-file) URIs.
