### ISSUE TITLE
logging jar and dependencies not added to the jetty9 image

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#95]
Here is a log of a docker container with the latest bits:
java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)
2015-09-25 13:47:00.456:WARN:oejx.XmlConfiguration:main: Config error at <Call name="init"><Arg><SystemProperty name="appengine_web_xml" default="WEB-INF/appengine-web.xml"/></Arg></Call> java.lang.reflect.InvocationTargetException in file:/var/lib/jetty/webapps/root.xml
2015-09-25 13:47:00.477:INFO:oejs.ServerConnector:main: Started ServerConnector@f45823b{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.util.TypeUtil.call(TypeUtil.java:515)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:726)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:358)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppDeployer.doStart(VmRuntimeWebAppDeployer.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
Caused by: java.lang.NoClassDefFoundError: com/google/apphosting/logging/JsonFormatter
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.init(VmRuntimeWebAppContext.java:244)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.google.apphosting.logging.JsonFormatter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by ludoch** [comment]
emergency fix applied for demos I need, but I think we need to make this area more automated (i.e adding dep jars in the lib/gae area).

**Comment by jboynes** [comment]
Adds #97 and #98 to address underlying cause
