### ISSUE TITLE
Cloud debugger does not seem to work with the jetty9 compat image

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#96]
I check the internal docker image we have, and Cloud debugger is working there.
But not from what we have in github.
The script diff I see is only this:
# Test if the argument is executable and if then run it directly
if type "$1" &>/dev/null; then
  exec "$@"
fi

in the jetty_run.sh script
Not sure what else is different..

**Comment by gregw** [comment]
Those extra lines are to conform to the docker policy of supporting 'docker run image bash' or similar.  If they are a problem for the debugger, then just remove them as they are not that important.

**Comment by ludoch** [comment]
I tried briefly, and the container did not start (no response)
Did not have time to debug

**Comment by gregw** [comment]
I'll be available this evening to help debug if need be.

**Comment by ludoch** [comment]
1 issue at least is that wget is not in the base image. I'll add it to the base jdk image.

**Comment by ludoch** [comment]
via ssh to the image, 
Info: Limiting Java heap size to: 2569M
/var/lib/jetty/jetty_run.sh: line 30: wget: command not found
/var/lib/jetty/jetty_run.sh: line 36: wget: command not found
Downloading Cloud Debugger agent from https://storage.googleapis.com/vm-config.openblend-demo.appspot.com/
/var/lib/jetty/jetty_run.sh: line 41: wget: command not found
tar (child): cdbg_java_agent.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/var/lib/jetty/jetty_run.sh: line 45: cdbg/format-env-appengine-vm.sh: No such file or directory
2015-09-25 17:06:31.606:INFO::main: Logging initialized @235ms
2015-09-25 17:06:32.239:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2015-09-25 17:06:32.287:INFO:oejs.AbstractNCSARequestLog:main: Opened /var/log/app_engine/request.2015_09_25.log
2015-09-25 17:06:32.532:INFO:oejs.ServerConnector:main: Started ServerConnector@310ba866{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.eclipse.jetty.util.TypeUtil.construct(TypeUtil.java:564)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:347)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259)
        at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppDeployer.doStart(VmRuntimeWebAppDeployer.java:72)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/conn/ClientConnectionManager
        at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.<init>(VmRuntimeWebAppContext.java:206)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.ClientConnectionManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 19 more

**Comment by gregw** [comment]
Ah -  wget was removed when we started assembling the maven depenencies with maven rather than with wget.  I didn't notice that it was needed by the run script.

I've not seen this put back, so I'll make a PR shortly.

**Comment by ludoch** [comment]
OK, so next step is how we set the Cloud Debugger for 'custom' runtimes, Since the Java8 work is pending, the 3 images produced here are seen as custom runtime in the backend deploy process, and it does not handle the Cloud debugger out of the box. Here is what the debugger lead says:

Here is how it works on MVM today:
   - During the deployment AppEngine (I think it's done in admin console) checks runtime ID. If it starts with "java", it copies cdbg_java_agent.tar.gz from Cloud Debugger GCS to application GCS.
   - We then sets gae_debugger_filename metadata to the URL of the debugger .tar.gz file in application GCS.
   - jetty_run.sh picks it up, downloads and enables the debugger.
The purpose of this elaborate mechanism is to ensure that:
   -  All instances use the same version of the debugger.
  -  Every time you redeploy, you get an up to date version of the debugger.
In the Java8 image:
  -  It is a custom runtime, so gae_debugger_filename metadata property is empty.
   - The jetty_run.sh script should not even try to download the debugger package, but it does for some reason (did you set CDBG_AGENT_URL environment variable?). It downloads some file from https://storage.googleapis.com/vm-config.openblend-demo.appspot.com/, but it's not .tar.gz., so it wouldn't work.

As a workaround if you set CDGB_AGENT_URL environment variable to https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz, everything should just work.

We need to fix it properly though. We can either extends the current mechanism to support custom runtimes, or we can just relax our two requirements for Cloud Debugger that is mentioned above and include cdbg_java_agent.tar.gz in Dockerfile.

**Comment by gregw** [comment]
Currently jetty_run.sh determines the value of CDGB_AGENT_URL with:
```shell
  CDBG_REF_URL="http://metadata/computeMetadata/v1/instance/attributes/gae_debugger_filename"
  if [[ -z "${CDBG_AGENT_URL}" ]]; then
    CDBG_AGENT_URL="https://storage.googleapis.com/vm-config.$(echo ${GAE_LONG_APP_ID} | sed -e 's/^\(.*\)\:\(.*\)$/\2.\1.a/g').appspot.com/"
    CDBG_AGENT_URL+="$( wget -q -O - "$@" --no-cookies --header "${METADATA_HEADER}" "${CDBG_REF_URL}" )"
  fi
```
If I understand the MVM advice you've reported, we can replace this code with simply setting the variable:
```shell
CDGB_AGENT_URL=https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz
```


The current script then downloads the agent with:
```shell
  echo "Downloading Cloud Debugger agent from ${CDBG_AGENT_URL}"
  AUTH_HEADER="Authorization: Bearer ${OAUTH_TOKEN}"
  wget -O cdbg_java_agent.tar.gz -nv --no-cookies -t 3 --header "${AUTH_HEADER}" "${CDBG_AGENT_URL}"
```

The MVM advice is that we don't download the agent at all?  But I can't see how that can work with just setting CDBG_AGENT_URL?   Perhaps the advice about that variable is just a work around until another mechanism automatically adds the agent files.

The proposed agent URL appears to be a public URL, so I don't believe that OAUTH is now needed and we could just do the wget.



The script then expands the tgz and determines the command line arguments with:
```shell
  # Extract the agent and format the command line arguments.
  mkdir -p cdbg ; tar xzf cdbg_java_agent.tar.gz -C cdbg
  DBG_AGENT="$( cdbg/format-env-appengine-vm.sh )"
```
This appears that it will still work with the agent that is downloadable from the proposed location.

So I'll prepare a PR that adheres to what I think the advice is... but I'm not yet sure I know how to test this.

**Comment by gregw** [comment]
I've created PR #105 that I believe follows the advice regarding the agent download.

I'm not yet familiar with how I can test the cloud debugger, but running manually within a boot2docker instance I can see the agent downloaded, installed and run. It produces output like:
```
root@2072edc34a88:/var/lib/jetty# java -agentpath:/var/lib/jetty/cdbg/cdbg_java_agent.so=--log_dir=/var/log/app_engine,--logtostderr=true,--cdbg_agentdir=/var/lib/jetty/cdbg,--cdbg_extra_class_path=/var/lib/jetty/webapps/root/WEB-INF/classes:/var/lib/jetty/webapps/root/WEB-INF/lib -jar /usr/local/jetty/start.jar 
I0927 23:05:08.424062    54 jvmti_globals.cc:300] Build time: Jul 16 2015 09:26:30
I0927 23:05:08.424195    54 jvmti_agent.cc:113] Java debuglet initialization started
I0927 23:05:08.424242    54 jvmti_agent.cc:154] Java debuglet initialization completed
I0927 23:05:08.492349    54 jvmti_agent.cc:163] Java VM started
I0927 23:05:08.497036    54 jvmti_agent.cc:173] JvmtiAgent::JvmtiOnVMInit initialization time: 4707 microseconds
I0927 23:05:08.497097    63 jvmti_agent_thread.cc:72] Agent thread started: CloudDebugger_main_worker_thread
I0927 23:05:08.499094    63 jvm_internals.cc:37] Loading class loader from /var/lib/jetty/cdbg/cdbg_java_agent_internals_loader.class
I0927 23:05:08.500098    63 jvm_internals.cc:335] Loading internals from /var/lib/jetty/cdbg/cdbg_java_agent_internals.jar
I0927 23:05:08.556953    63 jni_logger.cc:15] Initializing ClassPathLookup, default classpath: true, extra classpath: [/var/lib/jetty/webapps/root/WEB-INF/classes, /var/lib/jetty/webapps/root/WEB-INF/lib], config: /var/lib/jetty/cdbg/cdbg_config.xml
I0927 23:05:08.676368    63 jni_logger.cc:15] Total size of indexed resources database: 1026 bytes
I0927 23:05:08.680930    63 jvm_internals.cc:109] ClassPathLookup constructor time: 137863 microseconds
2015-09-27 23:05:08.957:INFO::main: Logging initialized @534ms
```
